import 'dotenv/config';
import express from 'express';
const app=express(); app.use(express.json({limit:'25mb'})); app.use(express.static('public'));
const BASE='https://api.meshy.ai';
function headers(){if(!process.env.MESHY_API_KEY)throw new Error('Brak MESHY_API_KEY w .env');return {Authorization:'Bearer '+process.env.MESHY_API_KEY,'Content-Type':'application/json'};}
async function meshy(path,options={}){const r=await fetch(BASE+path,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.detail||('Meshy HTTP '+r.status));return d;}
app.get('/api/health',(q,s)=>s.json({ok:true,meshyConfigured:Boolean(process.env.MESHY_API_KEY)}));
app.post('/api/meshy/text-to-3d',async(q,s)=>{try{const prompt=String(q.body.prompt||'').trim();if(!prompt)return s.status(400).json({error:'Podaj opis modelu.'});s.json(await meshy('/openapi/v2/text-to-3d',{method:'POST',body:JSON.stringify({mode:'preview',prompt:prompt.slice(0,800),ai_model:'latest',model_type:'standard',target_formats:['glb','stl','3mf'],auto_size:true,origin_at:'bottom'})}));}catch(e){s.status(500).json({error:e.message});}});
app.get('/api/meshy/text-to-3d/:id',async(q,s)=>{try{s.json(await meshy('/openapi/v2/text-to-3d/'+encodeURIComponent(q.params.id)));}catch(e){s.status(500).json({error:e.message});}});
app.post('/api/meshy/multi-image-to-3d',async(q,s)=>{try{const image_urls=Array.isArray(q.body.image_urls)?q.body.image_urls.slice(0,4):[];if(!image_urls.length)return s.status(400).json({error:'Dodaj przynajmniej jedno zdjęcie.'});s.json(await meshy('/openapi/v1/multi-image-to-3d',{method:'POST',body:JSON.stringify({image_urls,ai_model:'latest',geometry_resolution:'standard',should_texture:true,enable_pbr:true,target_formats:['glb','stl','3mf'],auto_size:true,origin_at:'bottom'})}));}catch(e){s.status(500).json({error:e.message});}});
app.get('/api/meshy/multi-image-to-3d/:id',async(q,s)=>{try{s.json(await meshy('/openapi/v1/multi-image-to-3d/'+encodeURIComponent(q.params.id)));}catch(e){s.status(500).json({error:e.message});}});
app.post('/api/payment/dummy',(q,s)=>{const ok=String(q.body.code||'')==='123456';s.status(ok?200:400).json(ok?{ok:true,status:'PAID',amount:49}:{ok:false,error:'Nieprawidłowy kod. Użyj 123456.'});});
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log('Persona 3D: http://localhost:'+port));